# Generated by Django 5.0.6 on 2024-06-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0004_alter_wallet_entity_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelapp.owner'),
        ),
    ]
