# Generated by Django 5.0.6 on 2024-06-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0005_alter_restaurant_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
