# Generated by Django 5.0.6 on 2024-06-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0007_alter_restaurant_name_alter_restaurant_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closes_at',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opens_at',
            field=models.TimeField(blank=True, default='00:00:00'),
        ),
    ]
