# Generated by Django 5.0.6 on 2024-06-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0010_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['restaurant'], name='modelapp_me_restaur_349bff_idx'),
        ),
    ]
