# Generated by Django 5.0.6 on 2024-06-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0011_menu_modelapp_me_restaur_349bff_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
