# Generated by Django 5.0.6 on 2024-06-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0013_restaurant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rider_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('RIDER_ON_WAY', 'Rider On Way'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PREPARING', max_length=100),
        ),
    ]
