# Generated by Django 5.0.6 on 2024-06-24 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0015_cart_cartitem_cart_modelapp_ca_user_id_966f60_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='modelapp_ca_cart_id_23a6be_idx',
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'item'], name='modelapp_ca_cart_id_297832_idx'),
        ),
    ]
