# Generated by Django 5.0.6 on 2024-06-25 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0017_cartitem_modelapp_ca_cart_id_23a6be_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_type',
            field=models.CharField(choices=[('CASH_ON_DELIVERY', 'Cash on Delivery'), ('STRIPE', 'Stripe')], default='CASH_ON_DELIVERY', max_length=20),
        ),
    ]
