# Generated by Django 5.0.6 on 2024-06-27 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0020_remove_order_owner_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=100),
        ),
    ]
