# Generated by Django 5.0.6 on 2024-07-01 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0025_alter_review_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='review',
            name='modelapp_re_order_i_365432_idx',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closes_at',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opens_at',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['order', 'review_type'], name='modelapp_re_order_i_135fe6_idx'),
        ),
    ]
