# Generated by Django 5.0.6 on 2024-07-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0026_remove_review_modelapp_re_order_i_365432_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant_images/'),
        ),
    ]
