# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0027_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
