# Generated by Django 5.0.6 on 2024-07-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0029_alter_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='stripe_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
