# Generated by Django 5.0.6 on 2024-07-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0030_menuitem_stripe_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='total_rating_population',
            field=models.IntegerField(default=0),
        ),
    ]
