# Generated by Django 5.0.6 on 2024-07-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0031_menuitem_total_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rated',
            field=models.BooleanField(default=False),
        ),
    ]
