# Generated by Django 5.0.6 on 2024-07-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0032_order_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
