# Generated by Django 5.0.6 on 2024-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0033_menuitem_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('FOOD', 'Food'), ('PLATFORM', 'Platform'), ('RESTAURANT', 'Restaurant')], max_length=100),
        ),
    ]
