# Generated by Django 5.0.6 on 2024-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0034_alter_review_review_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
