# Generated by Django 5.0.6 on 2024-07-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0035_alter_restaurant_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='total_rating_population',
            field=models.IntegerField(default=0),
        ),
    ]
