# Generated by Django 5.0.6 on 2024-07-27 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0037_rename_avg_rating_restaurant_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_in_string',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='RestaurantLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('location_in_string', models.CharField(blank=True, default='', max_length=500)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.restaurant')),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant'], name='modelapp_re_restaur_41082a_idx')],
            },
        ),
    ]
