# Generated by Django 5.0.6 on 2024-07-28 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0040_remove_menuitem_modelapp_me_menu_id_06d89e_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='stripe_price',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='StripeCheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=200)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='modelapp.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='modelapp_st_order_i_cc497e_idx'), models.Index(fields=['payment_intent'], name='modelapp_st_payment_f297ed_idx')],
            },
        ),
    ]
