# Generated by Django 5.0.6 on 2024-07-28 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0041_alter_menuitem_stripe_price_stripecheckoutsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='modelapp.order'),
        ),
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='payment_intent',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
