# Generated by Django 5.0.6 on 2024-07-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0042_alter_stripecheckoutsession_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecheckoutsession',
            name='intent_succeeded',
            field=models.BooleanField(default=False),
        ),
    ]
