# Generated by Django 5.0.6 on 2024-07-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0043_stripecheckoutsession_intent_succeeded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecheckoutsession',
            name='intent_succeeded',
        ),
        migrations.AlterField(
            model_name='stripecheckoutsession',
            name='payment_intent',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='StripeSuccessfulPaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=200)),
            ],
            options={
                'indexes': [models.Index(fields=['payment_intent'], name='modelapp_st_payment_4492df_idx')],
            },
        ),
    ]
