# Generated by Django 5.0.6 on 2024-07-29 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0044_remove_stripecheckoutsession_intent_succeeded_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('reply', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.user')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='modelapp_ch_user_id_5b154f_idx')],
            },
        ),
    ]
