# Generated by Django 5.0.6 on 2024-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0045_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_available_for_ride',
            field=models.BooleanField(default=False),
        ),
    ]
