# Generated by Django 5.0.6 on 2024-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0046_person_is_available_for_ride'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='ride_count',
            field=models.IntegerField(default=0),
        ),
    ]
