# Generated by Django 5.0.6 on 2024-08-08 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0048_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelapp.order'),
        ),
    ]
