# Generated by Django 5.0.6 on 2024-08-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0049_alter_message_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='modelapp_me_sender__69d65a_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='modelapp_me_receive_ee3dea_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='modelapp_me_message_3eab41_idx',
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['order'], name='modelapp_me_order_i_028d05_idx'),
        ),
    ]
