# Generated by Django 5.0.6 on 2024-08-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelapp', '0051_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='passwordreset',
            name='reset_token',
            field=models.CharField(default='34fasdfq43asdtq43afsasrjytu', max_length=300),
        ),
    ]
