# Generated by Django 5.0.6 on 2024-07-31 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
