# Generated by Django 5.0.6 on 2024-06-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoveredCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('city_image', models.ImageField(blank=True, null=True, upload_to='city_images/')),
                ('wiki_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Covered City',
                'verbose_name_plural': 'Covered Cities',
            },
        ),
    ]
