# Generated by Django 5.0.6 on 2024-05-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coveredcity',
            options={'verbose_name': 'Covered City', 'verbose_name_plural': 'Covered Cities'},
        ),
        migrations.AddField(
            model_name='coveredcity',
            name='wiki_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
